theme: minima
autor: ma-robles
description: p√°gina del curso
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/jekyll/jekyll" }
    - { platform: twitter, user_url: "https://twitter.com/jekyllrb" }
