title: Instrumentación Básica y Robótica (ENCiT 2024-1)
theme: minima
autor: Miguel Ángel Robles R.
description: El curso se desarrollará utilizando iteraciones, es decir secciones que retoman lo visto anteriormente agregando cosas nuevas.
locale: "es-mx"
twitter_username: miguelrsrn
github_username:  ma-robles
instagram_username: mi4rob
email: miguel.robles@atmosfera.unam.mx
